app/urls.py
from django.urls import path
from.import views

app_name = 'app'
urlpatterns = [
    path('home',views.index, name='index'),
    path('consultar-individuo/',views.consultarindividuo_view, name='consultar-individuo'),
    path('consultar-lista-individuos/',views.consultarlistaindividuos_view, name='consultar-lista-individuos'),
    path('consultar-partido/',views.consultarpartido_view, name='consultar-partido'),
    path('consultar-lista-partidos/',views.consultarlistapartidos_view, name='consultar-lista-partidos'),
    path('consultar-proceso/',views.consultarproceso_view, name='consultar-proceso'),

 
    path('afiliar-individuo/',views.afiliarindividuo_view, name='afiliar-individuo'),
    path('configuracion/',views.configuracion_view, name='configuracion'),
    path('crear-individuo/',views.crearindividuo_view, name='crear-individuo'),
    path('implicar-individuo/',views.implicarindividuo_view, name='implicar-individuo'),
    path('home-administrador/',views.homeadministrador_view, name='home-administrador'),
    path('',views.registro_view, name='registro'),

    path('crear-partido/',views.crearpartido_view, name='crear-partido'),
    path('aprobar-afiliacion/',views.aprobarafiliacion_view, name='aprobar-afiliacion'),
    path('aprobar-individuo/',views.aprobarindividuo_view, name='aprobar-individuo'),
    path('aprobar-proceso/',views.aprobarproceso_view, name='aprobar-proceso'),
    path('hab-des-ciudadano/',views.habdesciudadano_view, name='hab-des-ciudadano'),

    # login
    path('login/',views.login_view, name='login'),
    path('login_post/',views.login_post, name='login_post'),

    path('logout/', views.cerrar_sesion, name='cerrar_sesion'),
    path('registro/',views.form_registro_view, name='form_registro_view'),
    path('registro_post/',views.form_registro_post, name='form_registro_post'),

        # crearpartido
    path('crear-partido/crear',views.form_crear_partido_view, name='form_crear_partido_view'),
    path('crear-partido/crear_post',views.crear_partido_post, name='crear_partido_post'),
        # crearindividuo
    path('crear-individuo/crear',views.form_crear_individuo_view, name='form_crear_individuo_view'),
    path('crear-individuo/crear_post',views.crear_individuo_post, name='crear_individuo_post'),   
]

centinela_nube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/templates/app/AfiliarIndiv.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Centinela</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="{% static 'app/CSS/AfiliarIndiv.css' %}" />
  </head>
  <body>
    <div class="contenedor">
      <div class="header">
        <div class="fondo">
          <img src="{% static 'app/img/titulo.jpg' %}" alt="icono" />
        </div>
      </div>
      <div class="op">
        <div class="opt">
            <nav>
              <a href="{% url 'app:index' %}">Inicio</a>
              <a href="#{% url 'app:index' %}">Quienes somos</a>
              <a href="#{% url 'app:index' %}">Servicios</a>
              </nav>
        </div>
      </div>
      <div class="op2">
        <div class="opt2">
            <nav>
              <a href="{% url 'app:configuracion' %}">Configuracion</a>
              <a href="{% url 'app:registro' %}">Cerrar sesion</a>
              </nav>
        </div>
    </div>

      <div class="menu">
        <form action="#" target="1" method="get" name="DatosAssdicionales">
            <label for="correo">AFILIAR INDIVIDUO A PARTIDO: </label>
            <br />
            <label for="cnombre">Id de idividuo: </label>

                    <select id="items-i">
                      <option >1234</option>
                      <option >6789</option>
                      <option >1010</option>
                      <option >9988</option>
                      <option >2030</option>
                    </select>
            <br />
            <label for="cnombre">Id de partido: </label>

            <select id="items-i">
              <option >1234</option>
              <option >6789</option>
              <option >1010</option>
              <option >9988</option>
              <option >2030</option>
            </select>
            <br />
            <label for="correo">Fecha ingreso: </label>
            <input
              type="date"
              class="dirección"
              name="dirección"
              id="dirección"
              placeholder="Fecha de ingreso: "
              required
            />
            <br />
            <label for="password">Fecha de salida: </label>
            <input
              type="date"
              class="dirección"
              name="dirección"
              id="dirección"
              placeholder="Fecha de ingreso: "
              required
            />
            <br>
            <input type="submit" name="guardar" value="Guardar" />
          </form>
      </div>

      <div class="contenido">
       
      </div>

      <div class="footer">
         
      </div>

      <div class="cuadro">    
          
        </div>
    </div>
  </body>
</html>

app/templates/app/AprobarAfiliacion.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Centinela</title>
    <link rel="stylesheet" href="{% static 'app/CSS/administrador.css' %}" />
</head>
<body>
    <header>
        <div class="imagen-titulo">
          <a href="{% url 'app:home-administrador' %}">
            <img
              style="display: block; margin: auto"
              src="{% static 'app/img/titulo.jpg' %}"
              alt="centinela-titulo"
            />
          </a>
          <br />
        </div>
  
        <div class="menu">
          <nav>
            <a href="{% url 'app:index' %}">Inicio</a>
            <a href="#{% url 'app:index' %}">Quienes somos</a>
            <a href="#{% url 'app:index' %}">Servicios</a>
            <a href="{% url 'app:configuracion' %}">Configuracion</a>
            <a href="{% url 'app:registro' %}">Cerrar sesion</a>
          </nav>
          <br />
        </div>
      </header>

      <main>

        

        

       

        <section class="contenedor-aprobar-afiliacion">
            <div class="aprobar-afiliacion">
              <h2>Aprobar Afiliacion</h2>
            </div>
            <br>
            <div class="lista-afiliacion">

              <form name="formulario-afiliacion" method="post" action="#">
                    
                <p>
                    ID de la afiliacion:
                </p>

                <select id="items-a">
                  <option >98</option>
                  <option >87</option>
                  <option >76</option>
                  <option >65</option>
                  <option >54</option>
                </select>

                <input type="submit" name="enviar" value="Aprobar" />

              </form>

            </div>

        </section>

        
          <br>
          <div class="footer">
            <div class="fondofooter">
              <b>Plataforma que encuentra a los mañositos</b>
              <br />
              <br />
              <label>En Centinela estamos comprometidos con la justicia</label>
              <br />
              <label>social del pais y el correcto funconamiento de su</label>
              <br />
              <label>sistema democratico</label>
            </div>
          </div>

      
      </main>
</body>
</html>

app/templates/app/AprobarIndividuo.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Centinela</title>
    <link rel="stylesheet" href="{% static 'app/CSS/administrador.css' %}" />
</head>
<body>
    <header>
        <div class="imagen-titulo">
          <a href="{% url 'app:home-administrador' %}">
            <img
              style="display: block; margin: auto"
              src="{% static 'app/img/titulo.jpg' %}"
              alt="centinela-titulo"
            />
          </a>
          <br />
        </div>
  
        <div class="menu">
          <nav>
            <a href="{% url 'app:index' %}">Inicio</a>
            <a href="#{% url 'app:index' %}">Quienes somos</a>
            <a href="#{% url 'app:index' %}">Servicios</a>
            <a href="{% url 'app:configuracion' %}">Configuracion</a>
            <a href="{% url 'app:registro' %}">Cerrar sesion</a>
          </nav>
          <br />
        </div>
      </header>

      <main>



        <section class="contenedor-aprobar-individuo">
            <div class="aprobar-individuo">
                <h2>Aprobar individuo</h2>
            </div>
            <br>
            <div class="lista-individuo">
                <form name="formulario-individuo" method="post" action="#">
                    
                    <p>
                        ID del individuo:
                    </p>

                    <select id="items-i">
                      <option >1234</option>
                      <option >6789</option>
                      <option >1010</option>
                      <option >9988</option>
                      <option >2030</option>
                    </select>

                    <input type="submit" name="enviar" value="Aprobar" />

                  </form>
            </div>
            <br>

        </section>

        
          <br>
          <div class="footer">
            <div class="fondofooter">
              <b>Plataforma que encuentra a los mañositos</b>
              <br />
              <br />
              <label>En Centinela estamos comprometidos con la justicia</label>
              <br />
              <label>social del pais y el correcto funconamiento de su</label>
              <br />
              <label>sistema democratico</label>
            </div>
          </div>

 
      </main>
</body>
</html>

app/templates/app/ConsultarIndividuo.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Centinela</title>
    <link rel="stylesheet" href="{% static 'app/CSS/consultas.css' %}" />
</head>
<body>
    <header>
        <div class="imagen-titulo">
          <a href="index.html">
            <img
              style="display: block; margin: auto"
              src="{% static 'app/img/titulo.jpg' %}"
              alt="centinela-titulo"
            />
          </a>
          <br />
        </div>
  
        <div class="menu">
          <nav>
            <a href="{% url 'app:index' %}">Inicio</a>
            <a href="#{% url 'app:index' %}">Quienes somos</a>
            <a href="#{% url 'app:index' %}">Servicios</a>
            <a href="{% url 'app:configuracion' %}">Configuracion</a>
            <a href="{% url 'app:registro' %}">Cerrar sesion</a>
          </nav>
          <br />
        </div>
      </header>

      <main>

        <div class="titulo-consultas">
            <h1>Consultar individuo</h1>
        </div>
        <br>
        <section class="contenedor-consulta-individuo">


            <div class="consulta-datos-individuo">
                <form name="consulta-de-individuo" method="post" action="#">
                    
                    <p>
                        Nombre de individuo:
                    </p>

                    <select id="items-indiv">
                      <option >Vargas Andres</option>
                      <option >Pedreros Juan José</option>
                      <option >Melo Camilo</option>
                      <option >Cotrino Juan Pablo</option>
                      <option >Rodriguez Felipe</option>
                    </select>
    
                    <input type="submit" name="enviar" value="Buscar" />
    
                  </form>

            </div>
            <br>
            <div class="resultados-consulta-individuo">
                <table>

                    <tr>
                        <td>Apellidos</td>
                        <td>Nombres</td>
                        <td>Fecha de nacimiento</td>
                        <td>Cantidad de visitas</td>

                      </tr>
                      <td>#</td>
                      <td>#</td>
                      <td>#</td>
                      <td>#</td>
                    
                </table>
                <br>
                <h2>Lista de afiliaciones (Aprobadas)</h2>
                <br>
                <table>

                    <tr>
                        <td>Partido politico</td>
                        <td>Fecha de ingreso</td>
                        <td>Fecha de salida</td>


                      </tr>
                      <td>#</td>
                      <td>#</td>
                      <td>#</td>
 
                    
                </table>
                <br>
                <h2>Lista de procesos (Aprobados)</h2>
                <br>
                <table>

                    <tr>
                        <td>Fecha de inicio del proceso</td>
                        <td>Fecha fin del proceso</td>
                        <td>Titulo del proceso</td>
                        <td>Entidad</td>
                        <td>Monto</td>
                        <td>Comentarios del proceso</td>
                        <td>Abrierto/Cerrado</td>
                        <td>Acusacion</td>
                        <td>Culpable/Inocente</td>
                        <td>Pena</td>
                        <td>Comentarios de la implicacion</td>


                      </tr>
                      <td>#</td>
                      <td>#</td>
                      <td>#</td>
                      <td>#</td>
                      <td>#</td>
                      <td>#</td>
                      <td>#</td>
                      <td>#</td>
                      <td>#</td>
                      <td>#</td>
                      <td>#</td>
                      
 
                    
                </table>
            </div>
        </section>
        <br>
        <div class="footer">
            <div class="fondofooter">
              <b>Plataforma que encuentra a los mañositos</b>
              <br />
              <br />
              <label>En Centinela estamos comprometidos con la justicia</label>
              <br />
              <label>social del pais y el correcto funconamiento de su</label>
              <br />
              <label>sistema democratico</label>
            </div>
          </div>
        
      </main>
</body>
</html>

app/templates/app/CrearIndiv.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Centinela</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="{% static 'app/CSS/CrearIndiv.css' %}" />
  </head>
  <body>
    <div class="contenedor">
      <div class="header">
        <div class="fondo">
          <img src="{% static 'app/img/titulo.jpg' %}" alt="icono" />
        </div>
      </div>
      <div class="op">
        <div class="opt">
            <nav>
              <a href="{% url 'app:index' %}">Inicio</a>
              <a href="#{% url 'app:index' %}">Quienes somos</a>
              <a href="#{% url 'app:index' %}">Servicios</a>
              </nav>
        </div>
      </div>
      <div class="op2">
        <div class="opt2">
            <nav>
              <a href="{% url 'app:configuracion' %}">Configuracion</a>
              <a href="{% url 'app:registro' %}">Cerrar sesion</a>
              </nav>
        </div>
    </div>

      <div class="menu">
        <form action="{% url 'app:crear_individuo_post' %}"  method="POST" >
          {% csrf_token %}
            <label>CREAR INDIVIDUO</label>
            <br />
            <label >Nombre: </label>
            <input
              type="text"
              name="nombreindividuo"

              placeholder="Nombre"
              required
            />
            <br />
            <label>Apellido: </label>
            <input
              type="text"
              name="apellidoindividuo"

              placeholder="Apellido"
              required
            />
            
            <label>Fecha de nacimiento </label>
            <input
              type="date"

              name="fechaindividuo"

              placeholder="Fecha de nacimiento: "
              required
            />
            <br />
            <br>
              <input type="submit" name="guardar" value="Crear" />
        </form>
      </div>

      <div class="contenido">
        <form action="#" target="1" method="get" name="DatssosAdicionales">
          {% csrf_token %}
            <label for="correo">CREAR PROCESO</label>
            <br />
            <br>
            <label for="cnombre">Titulo: </label>
            <input
              type="text"
              name="nombre"
              id="nombre"
              placeholder="Titulo"
              required
            />
            <br />
            <br>
            <label for="cnombre">Fecha de inicio: </label>
            <input
              type="date"
              name="nombre"
              id="nombre"
              placeholder="Fecha de inicio"
              required
            />
            <br />
            <br>
            <label for="correo">Fecha finalización: </label>
            <input
              type="date"
              class="dirección"
              name="dirección"
              id="dirección"
              placeholder="Fecha finalización: "
              required
            />
            <br />
            <br>
            <label for="password">¿Proceso cerrado? </label>
            <input
              type="checkbox"
              name="telefono"
              id="telefono"
              placeholder="¿Proceso cerrado?: "
              required
              />
            <br />
            <br>
            <label for="correo">Entidad: </label>
            <input
              type="text"
              class="dirección"
              name="dirección"
              id="dirección"
              placeholder="Entidad: "
              required
            />
            <br />
            <label for="correo">Monto: </label>
            <input
              type="text"
              class="dirección"
              name="dirección"
              id="dirección"
              placeholder="Monto "
              required
            />
            <br />
            <label for="correo">Comentarios: </label>
            <input
              type="text"
              class="dirección"
              name="dirección"
              id="dirección"
              placeholder="Comentarios: "
              required
            />
            <br />
            <input type="submit" name="guardar" value="Guardar" />
          </form>
      </div>

      <div class="footer">
          
      </div>

      <div class="cuadro">    
        
        </div>
    </div>
  </body>
</html>

app/templates/app/HabDesCiudadano.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Centinela</title>
    <link rel="stylesheet" href="{% static 'app/CSS/administrador.css' %}" />
</head>
<body>
    <header>
        <div class="imagen-titulo">
          <a href="{% url 'app:home-administrador' %}">
            <img
              style="display: block; margin: auto"
              src="{% static 'app/img/titulo.jpg' %}"
              alt="centinela-titulo"
            />
          </a>
          <br />
        </div>
  
        <div class="menu">
          <nav>
            <a href="{% url 'app:index' %}">Inicio</a>
            <a href="#{% url 'app:index' %}">Quienes somos</a>
            <a href="#{% url 'app:index' %}">Servicios</a>
            <a href="{% url 'app:configuracion' %}">Configuracion</a>
            <a href="{% url 'app:registro' %}">Cerrar sesion</a>
          </nav>
          <br />
        </div>
      </header>

      <main>

        

        <section class="contenedor-habilitar-deshabilitar">
          <div class="habilitar-deshabilitar">
            <h2>Habilitar/Deshabilitar ciudadano</h2>
          </div>
          <br>
          <div class="lista-ciudadano">

            <form name="formulario-ciudadano" method="post" action="#">
                    
              <p>
                  ID del ciudadano:
              </p>

              <select id="items-c">
                <option >001</option>
                <option >002</option>
                <option >003</option>
                <option >004</option>
                <option >005</option>
              </select>
              <div class="botones-ciudadano">
                <input type="submit" name="enviar" value="Habilitar" />
                <input  type="submit" name="enviar" value="Deshabilitar" />

              </div>

            </form>

          </div>
          <br>
          <div class="footer">
            <div class="fondofooter">
              <b>Plataforma que encuentra a los mañositos</b>
              <br />
              <br />
              <label>En Centinela estamos comprometidos con la justicia</label>
              <br />
              <label>social del pais y el correcto funconamiento de su</label>
              <br />
              <label>sistema democratico</label>
            </div>
          </div>

        </section>
      </main>
</body>
</html>

app/templates/app/index.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Centinela</title>
    <link rel="stylesheet" href="{% static 'app/CSS/estilo.css' %}" />
  </head>
  <body>
    <header>
      <div class="imagen-titulo">
        <a href="{% url 'app:home-administrador' %}">
          <img
            style="display: block; margin: auto"
            src="{% static 'app/img/titulo.jpg' %}"
            alt="centinela-titulo"
          />
        </a>
        <br />
      </div>
      <div class="menu">
        <nav>
          <a href="{% url 'app:index' %}">Inicio</a>
          <a href="{% url 'app:index' %}">Quienes somos</a>
          <a href="{% url 'app:index' %}">Servicios</a>
          <a href="{% url 'app:configuracion' %}">Configuracion</a>
          <a href="{% url 'app:cerrar_sesion' %}">Cerrar sesion</a>
        </nav>
        <br />
      </div>
    </header>
    <main>
      <!-- {% if request.user.is_authenticated %}
      <h3>Bienvenido {{ request.user.first_name }}</h3>
      {% else %}
      <h3>El usuario no esta autenticado</h3>
      {% endif %} -->
      
      <section class="quienes-somos">
        <a name="quienes-somos"></a>
        <h2 class="titulo-uno">¿Quienes somos?</h2>

        <div class="contenedor-quienes-somos">
          <img src="{% static 'app/img/fraude.jpg' %}" alt="fraude" />
          <h3>Consulta anticorrupcion al alcance de todos</h3>
          <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque
            nihil voluptate recusandae placeat voluptatum quisquam corrupti est
            a velit rem. Corporis ut harum magni accusantium dolor ab ratione
            cupiditate. Officiis!
          </p>
          <h3>Promover el voto es promover el progreso</h3>
          <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatem
            eius vitae delectus accusamus odit recusandae fugit. Animi at culpa
            enim perferendis dolorum soluta eum adipisci, excepturi quidem
            cumque quia distinctio.
          </p>
        </div>
      </section>

      <section class="servicios">
        <a name="servicios"></a>
        <h2 class="titulo-dos">Servicios</h2>
        <div class="contenedor-servicios">
          <nav>
            <a href="{% url 'app:consultar-partido' %}">
              <img src="{% static 'app/img/consultadepartido.jpg' %}" alt="consulta de partido" />
            </a>
            <a href="{% url 'app:consultar-individuo' %}">
              <img
                src="{% static 'app/img/consultadeindividuo.jpg' %}"
                alt="consulta de individuo"
              />
            </a>
            <a href="{% url 'app:consultar-proceso' %}">
              <img src="{% static 'app/img/consultadeproceso.jpg' %}" alt="consulta de proceso" />
            </a>
          </nav>
          <br />
          <nav>
            <a href="{% url 'app:crear-individuo' %}">
              <img src="{% static 'app/img/crearindividuo.jpg' %}" alt="crear individuo" />
            </a>
            <a href="{% url 'app:afiliar-individuo' %}">
              <img src="{% static 'app/img/afiliarindividuo.jpg' %}" alt="afiliar individuo" />
            </a>
            <a href="{% url 'app:implicar-individuo' %}">
              <img src="{% static 'app/img/implicarafiliado.jpg' %}" alt="implicar afiliado" />
            </a>
          </nav>
        </div>
      </section>
      <br>
      <div class="footer">
        <div class="fondofooter">
          <b>Plataforma que encuentra a los mañositos</b>
          <br />
          <br />
          <label>En Centinela estamos comprometidos con la justicia</label>
          <br />
          <label>social del pais y el correcto funconamiento de su</label>
          <br />
          <label>sistema democratico</label>
        </div>
      </div>
    </main>
  </body>
</html>

app/templates/app/index2.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Centinela</title>
    <link rel="stylesheet" href="{% static 'app/CSS/estilo2.css' %}" />
  </head>
  <body>
    <header>
      <div class="imagen-titulo">
        <a href="{% url 'app:index' %}">
          <img
            style="display: block; margin: auto"
            src="{% static 'app/img/titulo.jpg' %}"
            alt="centinela-titulo"
          />
        </a>
        <br />
      </div>

      <div class="menu">
        <nav>
          <a href="{% url 'app:home-administrador' %}">Inicio</a>
          <a href="{% url 'app:home-administrador' %}">Quienes somos</a>
          <a href="{% url 'app:home-administrador' %}">Servicios</a>
          <a href="{% url 'app:configuracion' %}">Configuracion</a>
          <a href="{% url 'app:registro' %}">Cerrar sesion</a>
        </nav>
        <br />
      </div>
    </header>

    <main>
      <section class="quienes-somos">
        <a name="quienes-somos"></a>
        <h2 class="titulo-uno">¿Quienes somos?</h2>

        <div class="contenedor-quienes-somos">
          <img src="{% static 'app/img/fraude.jpg' %}" alt="fraude" />
          <h3>Consulta anticorrupcion al alcance de todos</h3>
          <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque
            nihil voluptate recusandae placeat voluptatum quisquam corrupti est
            a velit rem. Corporis ut harum magni accusantium dolor ab ratione
            cupiditate. Officiis!
          </p>
          <h3>Promover el voto es promover el progreso</h3>
          <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatem
            eius vitae delectus accusamus odit recusandae fugit. Animi at culpa
            enim perferendis dolorum soluta eum adipisci, excepturi quidem
            cumque quia distinctio.
          </p>
        </div>
      </section>

      <section class="servicios">
        <a name="servicios"></a>
        <h2 class="titulo-dos">Servicios</h2>
        <div class="contenedor-servicios">
          <nav>
            <a href="{% url 'app:consultar-partido' %}">
              <img src="{% static 'app/img/consultadepartido.jpg' %}" alt="consulta de partido" />
            </a>
            <a href="{% url 'app:consultar-individuo' %}">
              <img
                src="{% static 'app/img/consultadeindividuo.jpg' %}"
                alt="consulta de individuo"
              />
            </a>
            <a href="{% url 'app:consultar-proceso' %}">
              <img src="{% static 'app/img/consultadeproceso.jpg' %}" alt="consulta de proceso" />
            </a>
          </nav>
          <br />
          <nav>
            <a href="{% url 'app:crear-individuo' %}">
              <img src="{% static 'app/img/crearindividuo.jpg' %}" alt="crear individuo" />
            </a>
            <a href="{% url 'app:afiliar-individuo' %}">
              <img src="{% static 'app/img/afiliarindividuo.jpg' %}" alt="afiliar individuo" />
            </a>
            <a href="{% url 'app:implicar-individuo' %}">
              <img src="{% static 'app/img/implicarafiliado.jpg' %}" alt="implicar afiliado" />
            </a>
          </nav>
        </div>
<br>
        <div class="contenedor-servicios-admin">
            <h2  class="titulo-dos-admin">Servicios de administrador</h2>
            <nav>
            <a href="{% url 'app:crear-partido' %}">
                <img src="{% static 'app/img/crearpartido.jpg' %}" alt="crear partido">
            </a>
            <a href="{% url 'app:aprobar-individuo' %}">
                <img src="{% static 'app/img/aprobarindividuo.jpg' %}" alt="aprobar individuo">
            </a>
            <a href="{% url 'app:aprobar-proceso' %}">
                <img src="{% static 'app/img/aprobarproceso.jpg' %}" alt="aprobar proceso">
            </a>
            </nav>
            <br>
        <nav>
            <a href="{% url 'app:aprobar-afiliacion' %}">
                <img src="{% static 'app/img/aprobarafiliacion.jpg' %}" alt="aprobar afiliacion">
            </a>
            <a href="{% url 'app:hab-des-ciudadano' %}">
                <img src="{% static 'app/img/habilitardeshabilitar.jpg' %}" alt="habilitar deshabilitar">
            </a>
        </nav>
    <br>
        </div>
      </section>
      <br>
      <div class="footer">
        <div class="fondofooter">
          <b>Plataforma que encuentra a los mañositos</b>
          <br />
          <br />
          <label>En Centinela estamos comprometidos con la justicia</label>
          <br />
          <label>social del pais y el correcto funconamiento de su</label>
          <br />
          <label>sistema democratico</label>
        </div>
      </div>
    </main>
  </body>
</html>